### ISSUE TITLE
Hashable instances?

### ISSUE THREAD

**Issue by ocharles** [liyang/thyme#34]
What do you think about depending on the `hashable` library to provide `Hashable` instances for the various `thyme` data types?

**Comment by liyang** [comment]
I've been shying away from non-Platform packages, but `hashable` is not an unreasonable request.

I'll have a ponder on it and maybe include it the next time I have a few days to work on `thyme`: the documentation is sorely lacking and it's showing.

PS: Internally, we're using the `Enum` instances with [`enummapset-th`](http://hackage.haskell.org/package/enummapset-th).
