### ISSUE TITLE
A few obvious monoid instances?

### ISSUE THREAD

**Issue by pacak** [liyang/thyme#37]
```
instance Monoid NominalDiffTime where
    mempty = fromSeconds' 0
    mappend a b = a ^+^ b
```

**Comment by liyang** [comment]
It's obvious but it's not the only choice. You can use the alternative [`newtype Sum`](http://hackage.haskell.org/package/vector-space-0.10.2/docs/Data-AdditiveGroup.html#t:Sum) provided by `vector-space`.
