### ISSUE TITLE
`parseTAIUTCDAT` broken

### ISSUE THREAD

**Issue by kim** [liyang/thyme#38]
Due to an undocumented change (err, regression) in attoparsecs `rational` parsers (cf. bos/attoparsec#112), the `tai-utc.dat` file does no longer parse, which results in leap-second adjustments silently (!) not working.

A backwards-compatible (with older versions of attoparsec) fix could be:

```diff
diff --git a/src/Data/Thyme/Clock/TAI.hs b/src/Data/Thyme/Clock/TAI.hs
index b2fa7e9..7df8cd1 100644
--- a/src/Data/Thyme/Clock/TAI.hs
+++ b/src/Data/Thyme/Clock/TAI.hs
@@ -120,8 +120,8 @@ parseTAIUTCDAT = parse $ do
     tokens ["TAI", "-", "UTC", "="]
     b <- P.rational <?> "Base"
     tokens ["S", "+", "(", "MJD", "-"]
-    o <- P.rational <?> "Offset"
-    tokens [".", ")", "X"]
+    o <- P.rational <* optional (P.char '.') <?> "Offset"
+    tokens [")", "X"]
     c <- P.rational <* tokens ["S"] <?> "Coefficient"

     -- FIXME: confirm UTC↔TAI conversion for pre-1972.
```

**Comment by kim** [comment]
I would be willing to provide a proper patch for this, but would propose to refactor it a but, such that the `Parser` and a corresponding result datatype are exported. This would allow for easier testing, as well as more flexibility for constructing a `LeapSecondTable`.

What do you think?

**Comment by jamesdbrock** [comment]
Confirmed that @kim 's patch works.
