### ISSUE TITLE
Add to Stackage, cut new release, and possibly add GHC 8 support

### ISSUE THREAD

**Issue by jdreaver** [liyang/thyme#47]
Hey @liyang, have you considered adding `thyme` to Stackage? I know that @snoyberg used to be responsible for `thyme` in Stackage, but he recently stopped being the Stackage maintainer for it. I'm not sure where you're at with GHC 8 support, but I assume you would need to support GHC 8.

Also, are you planning on making a new release soon? Lot's of great stuff has been added to thyme since November of 2014 (when the last release was made), and I would love to use it without pointing to a git ref :)

If you are too busy to do this, I would love to help out! Also, thanks for making this package in the first place, it is a really awesome alternative to `time`.

**Comment by jamesdbrock** [comment]
Hi @jdreaver , Liyang is away from his computer for a while so he might not respond right away. He has done a lot of work to prepare *thyme* for GHC 8, and he is planning on making a new release soon.
