### ISSUE TITLE
How to efficiently convert UTCTime to/from Int64

### ISSUE THREAD

**Issue by ozataman** [liyang/thyme#62]
Unless I'm missing something, the library doesn't provide for a direct escape hatch conversion to/from Int64. This is however very helpful for a number of reasons:

- When doing custom UTCTime arithmetic (e.g. in timeseries libraries and similar, doing time-diff modulo arithmetic to figure out buckets, etc.)
- When writing `Serialize` and similar instances - much easier to just convert through the internal Int64.

I'm sure I must be missing something - what's the intended mechanism in support of these use cases?

Thanks!

**Comment by liyang** [comment]
You can use `posixTime . microseconds :: Iso' UTCTime Int64`.

Please close this issue if that addresses your question. Thanks.

**Comment by ozataman** [comment]
Thanks, I've been using that as well but wasn't sure if it'd be considered a reliable method. Closing.
