### ISSUE TITLE
A new version should be uploaded to Hackage

### ISSUE THREAD

**Issue by fumieval** [liyang/thyme#66]

**Comment by treeowl** [comment]
Yes, please. The version on Hackage has grown extremely old. What's the hang-up?

**Comment by jkachmar** [comment]
Is there any way to get some movement on this? 

It would be nice to have a current version of this library available on Hackage again!

**Comment by tmcgilchrist** [comment]
@liyang would it be possible to update this on hackage? I'd be happy to prepare an updated version suitable for recent versions of GHC, see https://github.com/liyang/thyme/compare/master...tmcgilchrist:thyme:master.

https://github.com/liyang/true-name/pull/4 also needs updating on hackage.

**Comment by treeowl** [comment]
Has anyone tried sending an email?

**Comment by fumieval** [comment]
@tmcgilchrist @treeowl Sorry, Although I took over the package on 2020 I've completely forgotten about this issue... I'll prepare a new release.

**Comment by treeowl** [comment]
@fumieval Please remember to update the maintainer info in the cabal file!

**Comment by tmcgilchrist** [comment]
Fantastic @fumieval Please also have a look at
https://github.com/tmcgilchrist/thyme/pull/1 for a working GitHub actions
CI.

**Comment by tmcgilchrist** [comment]
Thank you Fumiaki.
